//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azot_proj1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sensors()
        {
            this.warnings = new HashSet<warnings>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int sensor_type_id { get; set; }
        public Nullable<int> workshop_id { get; set; }
    
        public virtual sensor_types sensor_types { get; set; }
        public virtual workshop workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warnings> warnings { get; set; }
    }
}
